apiVersion: v1
kind: Service
metadata:  
  name: { { APP_NAME } }
spec:
  selector:    
    app: { { APP_NAME } }
  type: ClusterIP
  ports:  
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
